//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public short MaBinhLuan { get; set; }
        public Nullable<short> MaTaiKhoan { get; set; }
        public Nullable<short> MaPhim { get; set; }
        public string NoiDungBinhLuan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual Phim Phim { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
