//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonMuaLe
    {
        public short MaChiTiet { get; set; }
        public Nullable<short> MaDonMuaLe { get; set; }
        public Nullable<short> MaTaiKhoan { get; set; }
        public Nullable<short> MaKhachHang { get; set; }
        public string TenPhim { get; set; }
        public string LoaiPhim { get; set; }
        public string ChuDe { get; set; }
        public Nullable<System.DateTime> NgayDatPhim { get; set; }
        public Nullable<decimal> TongDonGia { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<short> MaPhim { get; set; }
        public string MaVoucher { get; set; }
    
        public virtual DonMuaPhimLe DonMuaPhimLe { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
