//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuDe_Phim
    {
        public short MaChuDe { get; set; }
        public short MaPhim { get; set; }
        public string MoTa { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
