//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonMuaGoiPhim
    {
        public short MaDonMuaGoi { get; set; }
        public Nullable<short> MaTaiKhoan { get; set; }
        public Nullable<short> MaKhachHang { get; set; }
        public Nullable<short> MaGoiPhim { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string MaVoucher { get; set; }
    
        public virtual GoiPhim GoiPhim { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
