//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonMuaPhimLe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonMuaPhimLe()
        {
            this.ChiTietDonMuaLes = new HashSet<ChiTietDonMuaLe>();
        }
    
        public short MaDonMuaLe { get; set; }
        public Nullable<short> MaTaiKhoan { get; set; }
        public Nullable<short> MaPhim { get; set; }
        public string TenPhim { get; set; }
        public Nullable<decimal> TongDonGia { get; set; }
        public string MaVoucher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonMuaLe> ChiTietDonMuaLes { get; set; }
        public virtual Phim Phim { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
