//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.ChiTietDonMuaLes = new HashSet<ChiTietDonMuaLe>();
            this.DonMuaGoiPhims = new HashSet<DonMuaGoiPhim>();
        }
    
        public short MaKhachHang { get; set; }
        public Nullable<short> MaTaiKhoan { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<byte> Tuoi { get; set; }
        public string email { get; set; }
        public Nullable<int> sdt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonMuaLe> ChiTietDonMuaLes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonMuaGoiPhim> DonMuaGoiPhims { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
