//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuXemPhim
    {
        public short MaTaiKhoan { get; set; }
        public short MaTapPhim { get; set; }
        public Nullable<System.DateTime> NgayXem { get; set; }
        public Nullable<System.DateTime> ThoiGianXem { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual TapPhim TapPhim { get; set; }
    }
}
