//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phim()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.ChiTietDonMuaLes = new HashSet<ChiTietDonMuaLe>();
            this.ChuDe_Phim = new HashSet<ChuDe_Phim>();
            this.DonMuaPhimLes = new HashSet<DonMuaPhimLe>();
            this.TapPhims = new HashSet<TapPhim>();
            this.Trailers = new HashSet<Trailer>();
            this.DienViens = new HashSet<DienVien>();
            this.QuangCaos = new HashSet<QuangCao>();
        }
    
        public short MaPhim { get; set; }
        public Nullable<short> MaTheLoai { get; set; }
        public Nullable<short> MaTrailer { get; set; }
        public Nullable<short> MaHopDong { get; set; }
        public string TenPhim { get; set; }
        public string TenDienVien { get; set; }
        public string HinhAnhPhim { get; set; }
        public string MoTaPhim { get; set; }
        public string ThoiLuongPhim { get; set; }
        public Nullable<System.DateTime> NamSanXuat { get; set; }
        public Nullable<short> MaQuocGia { get; set; }
        public Nullable<short> LuotXem { get; set; }
        public string DuongDanURL { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual BanQuyenPhim BanQuyenPhim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonMuaLe> ChiTietDonMuaLes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChuDe_Phim> ChuDe_Phim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonMuaPhimLe> DonMuaPhimLes { get; set; }
        public virtual QuocGia QuocGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        public virtual Trailer Trailer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TapPhim> TapPhims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trailer> Trailers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DienVien> DienViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuangCao> QuangCaos { get; set; }
    }
}
