//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TapPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TapPhim()
        {
            this.LichSuXemPhims = new HashSet<LichSuXemPhim>();
        }
    
        public short MaTapPhim { get; set; }
        public string TenTapPhim { get; set; }
        public string MoTa { get; set; }
        public string ThoiLuong { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string HinhAnh { get; set; }
        public string DuongDanURL { get; set; }
        public Nullable<short> MaPhim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuXemPhim> LichSuXemPhims { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
