//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongKeDoanhThu
    {
        public short MaThongKe { get; set; }
        public Nullable<System.DateTime> NgayThongKe { get; set; }
        public Nullable<short> MaAdmin { get; set; }
        public Nullable<byte> SoLuongPhim { get; set; }
        public Nullable<decimal> TongSoTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
