//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom3_WebXemPhim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trailer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trailer()
        {
            this.Phims = new HashSet<Phim>();
        }
    
        public short MaTrailer { get; set; }
        public string TenTrailer { get; set; }
        public string HinhAnh { get; set; }
        public string DuongDanURL { get; set; }
        public Nullable<short> MaPhim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phim> Phims { get; set; }
        public virtual Phim Phim { get; set; }
    }
}
